[theme]
primaryColor="#6C47FF"            # buttons, highlights
backgroundColor="#FFFFFF"         # main background
secondaryBackgroundColor="#F5F7FB" # used for containers
textColor="#111111"
font="sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
headless = true
port = 8501

[client]
toolbarMode = "minimal"           # cleaner top bar
showErrorDetails = false          # hides long error tracebacks from users

[browser]
gatherUsageStats = false
